version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: barista-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: barista_db
    ports:
      - "3307:3306" # Map to 3307 on host to avoid conflict with local MySQL
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: adeeb58/baristacoffee-backend:latest
    container_name: barista-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/barista_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysqldb
    restart: always

  frontend:
    image: adeeb58/baristacoffee-frontend:latest
    container_name: barista-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  mysql_data:
